const doctors = [
  {
    "id": "doc-1000",
    "name": "Dr. Anita Sharma",
    "specialty": "Cardiology",
    "bio": "Experienced practitioner. Demo profile.",
    "work_start": "6:00",
    "work_end": "16:00",
    "avg_seconds": 1200,
    "max_tokens": 40,
    "current_token": 3,
    "last_assigned": 12,
    "reserved": [],
    "status": "active"
  },
  {
    "id": "doc-1001",
    "name": "Dr. Rajesh Iyer",
    "specialty": "General Physician",
    "bio": "Experienced practitioner. Demo profile.",
    "work_start": "8:00",
    "work_end": "18:00",
    "avg_seconds": 300,
    "max_tokens": 100,
    "current_token": 1,
    "last_assigned": 13,
    "reserved": [],
    "status": "active"
  },
  {
    "id": "doc-1002",
    "name": "Dr. Kiran Menon",
    "specialty": "Orthopedics",
    "bio": "Experienced practitioner. Demo profile.",
    "work_start": "9:00",
    "work_end": "19:00",
    "avg_seconds": 300,
    "max_tokens": 80,
    "current_token": 4,
    "last_assigned": 17,
    "reserved": [],
    "status": "active"
  },
  {
    "id": "doc-1003",
    "name": "Dr. Priya Nair",
    "specialty": "Dermatology",
    "bio": "Experienced practitioner. Demo profile.",
    "work_start": "10:00",
    "work_end": "20:00",
    "avg_seconds": 1200,
    "max_tokens": 12,
    "current_token": 3,
    "last_assigned": 15,
    "reserved": [],
    "status": "active"
  },
  {
    "id": "doc-1004",
    "name": "Dr. Suresh Kumar",
    "specialty": "Pediatrics",
    "bio": "Experienced practitioner. Demo profile.",
    "work_start": "11:00",
    "work_end": "21:00",
    "avg_seconds": 600,
    "max_tokens": 100,
    "current_token": 3,
    "last_assigned": 6,
    "reserved": [],
    "status": "active"
  },
  {
    "id": "doc-1005",
    "name": "Dr. Meera Das",
    "specialty": "ENT",
    "bio": "Experienced practitioner. Demo profile.",
    "work_start": "12:00",
    "work_end": "22:00",
    "avg_seconds": 1800,
    "max_tokens": 100,
    "current_token": 4,
    "last_assigned": 14,
    "reserved": [],
    "status": "active"
  },
  {
    "id": "doc-1006",
    "name": "Dr. Arjun Varma",
    "specialty": "Neurology",
    "bio": "Experienced practitioner. Demo profile.",
    "work_start": "14:00",
    "work_end": "24:00",
    "avg_seconds": 1800,
    "max_tokens": 100,
    "current_token": 3,
    "last_assigned": 6,
    "reserved": [],
    "status": "active"
  },
  {
    "id": "doc-1007",
    "name": "Dr. Leena George",
    "specialty": "Gastroenterology",
    "bio": "Experienced practitioner. Demo profile.",
    "work_start": "15:00",
    "work_end": "25:00",
    "avg_seconds": 300,
    "max_tokens": 12,
    "current_token": 3,
    "last_assigned": 15,
    "reserved": [],
    "status": "active"
  },
  {
    "id": "doc-1008",
    "name": "Dr. Thomas Mathew",
    "specialty": "Urology",
    "bio": "Experienced practitioner. Demo profile.",
    "work_start": "16:00",
    "work_end": "26:00",
    "avg_seconds": 1800,
    "max_tokens": 60,
    "current_token": 3,
    "last_assigned": 16,
    "reserved": [],
    "status": "active"
  },
  {
    "id": "doc-1009",
    "name": "Dr. Radhika Pillai",
    "specialty": "Endocrinology",
    "bio": "Experienced practitioner. Demo profile.",
    "work_start": "18:00",
    "work_end": "28:00",
    "avg_seconds": 600,
    "max_tokens": 80,
    "current_token": 5,
    "last_assigned": 15,
    "reserved": [],
    "status": "active"
  }
];
export default doctors;